services:
  file-mover:
    image: rcortese/file-mover:latest
    volumes:
      - /local/path:/source_folder
    environment:
      DEST_SMB: //server/share
      SMB_USERNAME: user
      SMB_PASSWORD: pass
    # Allow the container to mount the SMB share
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
